# Generated by Django 4.1.13 on 2024-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.CharField(max_length=1000)),
                ("receiver_id", models.CharField(max_length=1000)),
                ("content", models.CharField(max_length=1000)),
                ("timeStamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserMessagePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.CharField(max_length=1000)),
                ("receiver_id", models.CharField(max_length=1000)),
            ],
        ),
    ]
